-- Equivalent SQL for:
-- app/Database/Migrations/2026-05-18-000001_CreateUniversityCollegeSupportTables.php

CREATE TABLE IF NOT EXISTS `university_college_tutors` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int unsigned DEFAULT NULL,
  `username` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `reference_code` varchar(30) COLLATE utf8mb4_general_ci NOT NULL,
  `full_name` varchar(150) COLLATE utf8mb4_general_ci NOT NULL,
  `email` varchar(150) COLLATE utf8mb4_general_ci NOT NULL,
  `phone` varchar(30) COLLATE utf8mb4_general_ci NOT NULL,
  `profile_picture` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `national_id_file` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `certification_files_json` text COLLATE utf8mb4_general_ci NOT NULL,
  `institutions_json` text COLLATE utf8mb4_general_ci NOT NULL,
  `specializations_json` text COLLATE utf8mb4_general_ci NOT NULL,
  `service_areas_json` text COLLATE utf8mb4_general_ci NOT NULL,
  `year_of_study_or_graduation` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `bio` text COLLATE utf8mb4_general_ci NOT NULL,
  `references_json` text COLLATE utf8mb4_general_ci,
  `work_status` varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `employer_name` varchar(150) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `employer_contact` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `available_days_json` text COLLATE utf8mb4_general_ci NOT NULL,
  `preferred_times_json` text COLLATE utf8mb4_general_ci NOT NULL,
  `teaching_mode` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `city_location` varchar(150) COLLATE utf8mb4_general_ci NOT NULL,
  `hourly_rate` decimal(12,2) DEFAULT NULL,
  `consultation_package_rate` decimal(12,2) DEFAULT NULL,
  `dissertation_package_rate` decimal(12,2) DEFAULT NULL,
  `exam_preparation_rate` decimal(12,2) DEFAULT NULL,
  `subscription_plan` varchar(30) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'Basic',
  `status` varchar(30) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'pending_review',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `reference_code` (`reference_code`),
  KEY `user_id` (`user_id`),
  KEY `username` (`username`),
  KEY `email` (`email`),
  KEY `phone` (`phone`),
  KEY `teaching_mode` (`teaching_mode`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `university_lecture_requests` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `reference_code` varchar(30) COLLATE utf8mb4_general_ci NOT NULL,
  `full_name` varchar(150) COLLATE utf8mb4_general_ci NOT NULL,
  `email` varchar(150) COLLATE utf8mb4_general_ci NOT NULL,
  `phone` varchar(30) COLLATE utf8mb4_general_ci NOT NULL,
  `institution` varchar(150) COLLATE utf8mb4_general_ci NOT NULL,
  `service_category` varchar(80) COLLATE utf8mb4_general_ci NOT NULL,
  `topic` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `delivery_mode` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `city_location` varchar(150) COLLATE utf8mb4_general_ci NOT NULL,
  `preferred_date` date DEFAULT NULL,
  `preferred_time` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `budget_range` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `notes` text COLLATE utf8mb4_general_ci,
  `status` varchar(30) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'open',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `reference_code` (`reference_code`),
  KEY `service_category` (`service_category`),
  KEY `delivery_mode` (`delivery_mode`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
