-- Japan teaching opportunity application table
-- Run this script inside the target TutorConnect database, for example: tutorconnectmw

CREATE TABLE IF NOT EXISTS `japan_teaching_applications` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `application_reference` VARCHAR(40) NOT NULL,
    `full_name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(150) NOT NULL,
    `phone` VARCHAR(30) DEFAULT NULL,
    `nationality` VARCHAR(100) DEFAULT NULL,
    `gender` VARCHAR(20) DEFAULT NULL,
    `date_of_birth` DATE DEFAULT NULL,
    `age` INT(3) DEFAULT NULL,
    `current_address` TEXT DEFAULT NULL,
    `has_valid_passport` TINYINT(1) NOT NULL DEFAULT 0,
    `passport_number` VARCHAR(100) DEFAULT NULL,
    `passport_expiry_date` DATE DEFAULT NULL,
    `willing_to_renew_passport` TINYINT(1) NOT NULL DEFAULT 0,
    `highest_qualification` VARCHAR(150) DEFAULT NULL,
    `degree_obtained` VARCHAR(150) DEFAULT NULL,
    `field_of_study` VARCHAR(150) DEFAULT NULL,
    `institution_name` VARCHAR(255) DEFAULT NULL,
    `year_of_completion` INT(4) DEFAULT NULL,
    `has_teaching_certificate` TINYINT(1) NOT NULL DEFAULT 0,
    `teaching_certificate_details` TEXT DEFAULT NULL,
    `has_teaching_experience` TINYINT(1) NOT NULL DEFAULT 0,
    `teaching_experience_location` TEXT DEFAULT NULL,
    `subjects_taught` TEXT DEFAULT NULL,
    `level_taught` VARCHAR(50) DEFAULT NULL,
    `teaching_experience_duration` VARCHAR(100) DEFAULT NULL,
    `documents_already_shared` TINYINT(1) NOT NULL DEFAULT 0,
    `shared_documents_note` TEXT DEFAULT NULL,
    `financial_readiness_json` LONGTEXT DEFAULT NULL,
    `referees_json` LONGTEXT DEFAULT NULL,
    `declarations_json` LONGTEXT DEFAULT NULL,
    `degree_document_path` VARCHAR(255) DEFAULT NULL,
    `transcript_document_path` VARCHAR(255) DEFAULT NULL,
    `passport_copy_path` VARCHAR(255) DEFAULT NULL,
    `teaching_certificate_path` VARCHAR(255) DEFAULT NULL,
    `cv_document_path` VARCHAR(255) DEFAULT NULL,
    `intro_video_path` VARCHAR(255) DEFAULT NULL,
    `application_fee_amount` DECIMAL(10,2) NOT NULL DEFAULT 10000.00,
    `processing_fee_amount` DECIMAL(10,2) NOT NULL DEFAULT 350000.00,
    `status` VARCHAR(30) NOT NULL DEFAULT 'submitted',
    `admin_notes` TEXT DEFAULT NULL,
    `submitted_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME DEFAULT NULL,
    `updated_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_japan_teaching_applications_reference` (`application_reference`),
    KEY `idx_japan_teaching_applications_email` (`email`),
    KEY `idx_japan_teaching_applications_status` (`status`),
    KEY `idx_japan_teaching_applications_submitted_at` (`submitted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
